name: website

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --with docs
          poetry run python -m pip install --upgrade pip
          poetry run pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          poetry run pip install lightning
      - run: poetry run python ./docs/make.py ${{ github.event.release.tag_name }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/api/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
